### ISSUE TITLE
Error in reading xtf file for innerFunction ch.so.agi.avgbs2mtab.readxtf.ReadXtf

### ISSUE THREAD

**Issue by Luescher** [sogis/avgbs2mtab#1]
Folgende Meldung erscheint: 

Error in reading xtf file for innerFunction  ch.so.agi.avgbs2mtab.readxtf.ReadXtf$$Lambda$9/906272996@1d83b060

[SO0200002578_39732-01_20170908.zip](https://github.com/sogis/avgbs2mtab/files/1291497/SO0200002578_39732-01_20170908.zip)

**Comment by edigonzales** [comment]
Im Logfile des Services steht mehr:

`Caused by: java.lang.NumberFormatException: For input string: "893.0"`
	`at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)`
	`at java.lang.Integer.parseInt(Integer.java:580)`
	`at java.lang.Integer.parseInt(Integer.java:615)`
	`at ch.so.agi.avgbs2mtab.readxtf.ReadXtf.getDRPMetadata(ReadXtf.java:157)`
	`at ch.so.agi.avgbs2mtab.readxtf.ReadXtf.parseTransferFile(ReadXtf.java:76)`

Im Modell für `Flaechenmass` sind Dezimalwerte erlaubt. In unserem Fall (Kanton Solothurn) müssen sie aber immer ganzzahlig sein. Also "eigentlich" Integer-Werte. 

Integer.parseInt() erwartet einen Integer-Wert und kann mit "893.0" nichts anfangen.

**Comment by barpastu** [comment]
Sollte mit Commit 3a3d67e07adc9f297dbb1b694fa202320e91afec wieder funktionieren.

**Comment by edigonzales** [comment]
Sämtliche Grundstücksnummern werden als Integer ausgelesen. Soll das so bleiben? Dh. es fliegt uns um die Ohren wenn - für Kanton SO fälschlicherweise - mal was anderes drinsteht.

@Luescher ?

**Comment by Luescher** [comment]
In Solothurn darf es keine Grundstücksnummern als Text oder Dezimale geben (im Capitastra, Grundbuch-Software, ist die Grundstücknr. ein Integer). Um die Ohren sollte es aber nicht fliegen. Ist es möglich, dass eine Fehlermeldung angezeigt wird die verständlich ist, falls dieser Fall eintritt?
